services:
  db:
    container_name: postgresdb
    image: postgres:16.4-alpine3.20
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "motordb"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  jobscrapper_api:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: jobscrapper_api
    ports:
      - 3333:3333
    command: sh -c "npx ts-node ./node_modules/typeorm/cli.js migration:run -d src/database/data-source.ts && npm run dev"
    volumes:
      - ../.:/app
    env_file:
      - ../.env
    environment:
      - DATABASE_HOST
      - DATABASE_USER
      - DATABASE_PASS
      - DATABASE_NAME
      - DATABASE_PORT
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
